version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "8083:80"
    restart: on-failure
    volumes:
      - './:/var/www/app:ro'
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: .
    working_dir: /var/www/app/
    volumes:
      - './:/var/www/app/'